name: Publish to GitHub Packages
on:
  push:
    branches: [ main ]
#env:
#  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_SIGNING_KEY }}
#  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Publish package
        run: echo "uncomment code below"
#        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  code-coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'
#      - name: Cache Gradle packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
#          restore-keys: ${{ runner.os }}-gradle
#      - name: Assemble with Gradle
#        run: ./gradlew assemble
#      - name: Generate coverage by running tests
#        run: ./gradlew test
#      - name: Publish Code Coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
#          directory: ./coverage/reports/
#          fail_ci_if_error: true
#          verbose: true
